### ISSUE TITLE
brew upgrade shtools Error: SHA256 mismatch.

### ISSUE THREAD

**Issue by xiaoledeng** [SHTOOLS/SHTOOLS#291]
**Description of the problem**

The problem is Error: SHA256 mismatch.

**System information**

➜  ~ brew upgrade shtools
==> Upgrading 1 outdated package:
shtools/shtools/shtools 4.6.2 -> 4.7.1
==> Upgrading shtools/shtools/shtools 4.6.2 -> 4.7.1 --with-openmp
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/fftw-3.3.9.big_sur.bottle.tar.gz
Already downloaded: /Users/shalom/Library/Caches/Homebrew/downloads/ee4e328feedd71db8f645d80fd4eb7347d6b52399c25d7fbe46c03ec637cd50b--fftw-3.3.9.big_sur.bottle.tar.gz
==> Downloading https://github.com/SHTOOLS/SHTOOLS/archive/v4.7.1.tar.gz
Already downloaded: /Users/shalom/Library/Caches/Homebrew/downloads/258a8fae83c0b8a362e27579c115a9251c4bdd9738846e7c930f2a8bc73ae2ac--SHTOOLS-4.7.1.tar.gz
Error: SHA256 mismatch
Expected: 6ed2130eed7b741df3b19052b29b3324601403581c7b9afb015e0370e299a2bd
  Actual: 5b906e79a66bce5fbf8ac1e9d55fcc3366a86cb42762f910331a06794596fbf2
    File: /Users/shalom/Library/Caches/Homebrew/downloads/258a8fae83c0b8a362e27579c115a9251c4bdd9738846e7c930f2a8bc73ae2ac--SHTOOLS-4.7.1.tar.gz
To retry an incomplete download, remove the file above.

**Comment by MarkWieczorek** [comment]
Could you try `brew update` first? The newest version is 4.8. Some of the older versions have problems with the hashes not matching because of a problem with how github generates tarballs on the fly. This should be fixed in 4.8+.

**Comment by xiaoledeng** [comment]
Yes, I have tried `brew update` firstly. But the error of SHA256 mismatch still exists.

**Comment by xiaoledeng** [comment]
> Yes, I have tried `brew update` firstly. But the error of SHA256 mismatch still exists.

➜  brew update
Error: Fetching /usr/local/Homebrew/Library/Taps/shtools/homebrew-shtools failed!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Casks
northernspysoftware-colorpicker
==> Updated Casks
chromium                     emacs                        mgba                         nova                         tipp10                       whalebird
cutter                       flutter                      mountain-duck                programmer-dvorak            vmware-fusion                yinxiangbiji
devonthink                   goodsync                     netron                       raspberry-pi-imager          wechatwebdevtools            zoom-for-it-admins
==> Deleted Casks
craft

You have 4 outdated formulae installed.
You can update them with brew upgrade.

➜  brew upgrade
==> Upgrading 4 outdated packages:
shtools/shtools/shtools 4.6.2 -> 4.7.1
ghc 8.8.1 -> 8.10.4
axel 2.17.9 -> 2.17.10
fftw 3.3.8_2 -> 3.3.9
==> Upgrading shtools/shtools/shtools 4.6.2 -> 4.7.1 --with-openmp
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/fftw-3.3.9.big_sur.bottle.tar.gz
Already downloaded: /Users/shalom/Library/Caches/Homebrew/downloads/ee4e328feedd71db8f645d80fd4eb7347d6b52399c25d7fbe46c03ec637cd50b--fftw-3.3.9.big_sur.bottle.tar.gz
==> Downloading https://github.com/SHTOOLS/SHTOOLS/archive/v4.7.1.tar.gz
Already downloaded: /Users/shalom/Library/Caches/Homebrew/downloads/258a8fae83c0b8a362e27579c115a9251c4bdd9738846e7c930f2a8bc73ae2ac--SHTOOLS-4.7.1.tar.gz
Error: SHA256 mismatch
Expected: 6ed2130eed7b741df3b19052b29b3324601403581c7b9afb015e0370e299a2bd
  Actual: 5b906e79a66bce5fbf8ac1e9d55fcc3366a86cb42762f910331a06794596fbf2
    File: /Users/shalom/Library/Caches/Homebrew/downloads/258a8fae83c0b8a362e27579c115a9251c4bdd9738846e7c930f2a8bc73ae2ac--SHTOOLS-4.7.1.tar.gz
To retry an incomplete download, remove the file above.

**Comment by MarkWieczorek** [comment]
Could you do `brew info shtools` to see what is the latest version? Also try installing 4.8 by `brew install shtools@4.8`. In the worst case, you could try `brew install shtools --HEAD` that should install from the source on github.

If you are using a new apple silicon computer, let me know. I'm not sure if there are builds for this

**Comment by xiaoledeng** [comment]
➜  ~ brew info shtools
shtools: stable 4.8 (bottled), HEAD
Spherical Harmonic Tools
https://shtools.github.io/SHTOOLS/
/usr/local/Cellar/shtools/4.6.2 (130 files, 3.0MB) *
  Built from source on 2020-09-09 at 09:03:38 with: --with-openmp
From: https://mirrors.ustc.edu.cn/homebrew-core.git/Formula/shtools.rb
License: BSD-3-Clause
==> Dependencies
Required: fftw ✔, gcc ✔, openblas ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 6 (30 days), 34 (90 days), 78 (365 days)
install-on-request: 6 (30 days), 34 (90 days), 78 (365 days)
build-error: 0 (30 days)


 ➜  ~ brew install shtools@4.8
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "shtools@4.8".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by xiaoledeng** [comment]
Yes, I am using the newest macOS with version 11.2.3.

**Comment by xiaoledeng** [comment]
Thanks a lot. This problem is solved with `brew install shtools --HEAD`.

➜  ~ brew install shtools --HEAD
==> Cloning https://github.com/SHTOOLS/SHTOOLS.git
Updating /Users/shalom/Library/Caches/Homebrew/shtools--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 663d267 Merge pull request #283 from SHTOOLS/develop
Error: shtools 4.6.2 is already installed
To install HEAD-663d267, first run:
  brew unlink shtools

➜  ~ brew unlink shtools
Unlinking /usr/local/Cellar/shtools/4.6.2... 125 symlinks removed.

 ➜  ~ brew install shtools --HEAD
==> Cloning https://github.com/SHTOOLS/SHTOOLS.git
Updating /Users/shalom/Library/Caches/Homebrew/shtools--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 663d267 Merge pull request #283 from SHTOOLS/develop
==> make fortran
==> make fortran-mp
🍺  /usr/local/Cellar/shtools/HEAD-663d267: 162 files, 19.5MB, built in 1 minute
Removing: /usr/local/Cellar/shtools/4.6.2... (130 files, 3.0MB)
Removing: /Users/shalom/Library/Caches/Homebrew/shtools--4.7.1.tar.gz... (33.5MB)
Removing: /Users/shalom/Library/Caches/Homebrew/shtools--4.8.big_sur.bottle.tar.gz... (7.5MB)
